export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  REGISTER_PENDING: "REGISTER_PENDING",
  LOGIN_PENDING: "LOGIN_PENDING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_USER: "LOGOUT_USER",
};
